#!/usr/bin/env python3
import sys
import os

# Ensure the parent directory of yasinhub is in sys.path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from yasinhub.cli import main

if __name__ == "__main__":
    sys.exit(main())
