import { parseRoute, onRouteChange, navKey } from "./js/router.js";
import * as api from "./js/api.js";
import { renderLoading, renderError, renderOverview, renderExecutionsList, renderExecutionDetail, renderFleetsList, renderFleetDetail, renderEventsTimeline, formatControlError } from "./js/views.js";
const TITLES={overview:"Overview / System Status",executions:"Executions","execution-detail":"Execution Detail",fleets:"Fleets","fleet-detail":"Fleet Detail",events:"Events"};
const POLL_LIST_MS=5000,POLL_DETAIL_MS=3000;
const appState={fetchedAt:null,routeKey:null,hasContent:false,pollTimer:null,fetchGen:0};
const $=(id)=>document.getElementById(id);
function setConnectionStatus(){const el=$("connection-status");if(!el)return;const online=navigator.onLine;el.textContent=online?"Online":"Offline";el.className="connection-status "+(online?"status-online":"status-offline");}
function setStale(stale){const el=$("stale-indicator");if(el)el.hidden=!stale;}
function setTitle(route){const title=TITLES[route.name]||"YasinHub";const el=$("page-title");if(el)el.textContent=title;document.title=title+" · YasinHub";}
function setActiveNav(route){const key=navKey(route);document.querySelectorAll("[data-nav]").forEach(a=>a.classList.toggle("active",a.getAttribute("data-nav")===key));}
function routeKey(route){return route.name+":"+(route.params.id||"");}
function updateMetaRow(){let row=$("live-meta");if(!row){const heading=document.querySelector(".page-heading");if(!heading)return;row=document.createElement("div");row.id="live-meta";row.className="meta-row";heading.insertAdjacentElement("afterend",row);}const ts=appState.fetchedAt?new Date(appState.fetchedAt).toLocaleTimeString():"—";const live=appState.pollTimer!=null&&navigator.onLine&&!document.hidden;row.innerHTML=`${live?'<span class="live-dot" title="Live polling"></span><span>Live</span>':"<span>Idle</span>"}<span>Updated ${ts}</span>`;}
function stopPolling(){if(appState.pollTimer!=null){clearInterval(appState.pollTimer);appState.pollTimer=null;}}
function startPolling(route){stopPolling();if(!navigator.onLine||document.hidden){updateMetaRow();return;}const ms=route.name==="execution-detail"||route.name==="fleet-detail"?POLL_DETAIL_MS:POLL_LIST_MS;appState.pollTimer=setInterval(()=>{if(!document.hidden&&navigator.onLine)renderRoute(parseRoute(),{soft:true});},ms);updateMetaRow();}
async function renderRoute(route,opts={}){const soft=Boolean(opts.soft),content=$("content");if(!content)return;const key=routeKey(route);if(key!==appState.routeKey){appState.routeKey=key;setTitle(route);setActiveNav(route);appState.hasContent=false;}setConnectionStatus();if(!soft||!appState.hasContent)renderLoading(content,soft?"Refreshing…":"Loading…");const gen=++appState.fetchGen;try{
  if(route.name==="overview"){
    const [result,statusRes]=await Promise.all([api.getSystemDashboard(),api.getSystemStatus()]);if(gen!==appState.fetchGen)return;if(result.offline){renderError(content,"Offline — cannot load system status.",true);setStale(true);appState.hasContent=false;return;}if(!result.ok){renderError(content,result.message||"Failed to load system status.");setStale(true);appState.hasContent=false;return;}const projects=statusRes&&statusRes.ok&&statusRes.data&&Array.isArray(statusRes.data.projects)?statusRes.data.projects:[];renderOverview(content,result.data,projects);appState.fetchedAt=Date.now();appState.hasContent=true;setStale(false);updateMetaRow();return;
  }
  if(route.name==="executions"){const r=await api.listExecutions();if(gen!==appState.fetchGen)return;if(r.offline){renderError(content,"Offline — cannot load executions.",true);setStale(true);return;}if(!r.ok){renderError(content,r.message||"Failed to load executions.");setStale(true);return;}renderExecutionsList(content,r.executions||[]);appState.fetchedAt=Date.now();appState.hasContent=true;setStale(false);updateMetaRow();return;}
  if(route.name==="execution-detail"){const id=route.params.id,[execRes,eventsRes]=await Promise.all([api.getExecution(id),api.listExecutionEvents(id)]);if(gen!==appState.fetchGen)return;if(execRes.offline){renderError(content,"Offline — cannot load execution.",true);setStale(true);return;}if(!execRes.ok||!execRes.execution){renderError(content,execRes.status===404?"Execution not found (404).":execRes.message||"Failed to load execution.");setStale(true);return;}renderExecutionDetail(content,execRes.execution,eventsRes.ok?eventsRes.events||[]:[]);appState.fetchedAt=Date.now();appState.hasContent=true;setStale(!eventsRes.ok);updateMetaRow();wireControls(content);return;}
  if(route.name==="fleets"){const r=await api.listFleets();if(gen!==appState.fetchGen)return;if(r.offline){renderError(content,"Offline — cannot load fleets.",true);setStale(true);return;}if(!r.ok){renderError(content,r.message||"Failed to load fleets.");setStale(true);return;}renderFleetsList(content,r.fleets||[]);appState.fetchedAt=Date.now();appState.hasContent=true;setStale(false);updateMetaRow();return;}
  if(route.name==="fleet-detail"){const r=await api.getFleet(route.params.id);if(gen!==appState.fetchGen)return;if(r.offline){renderError(content,"Offline — cannot load fleet.",true);setStale(true);return;}if(!r.ok||!r.fleet){renderError(content,r.status===404?"Fleet not found (404).":r.message||"Failed to load fleet.");setStale(true);return;}renderFleetDetail(content,r.fleet);appState.fetchedAt=Date.now();appState.hasContent=true;setStale(false);updateMetaRow();wireControls(content);return;}
  if(route.name==="events"){const r=await api.listEvents({limit:100});if(gen!==appState.fetchGen)return;if(r.offline){renderError(content,"Offline — cannot load events.",true);setStale(true);return;}if(!r.ok){renderError(content,r.message||"Failed to load events.");setStale(true);return;}renderEventsTimeline(content,r.events||[]);appState.fetchedAt=Date.now();appState.hasContent=true;setStale(false);updateMetaRow();return;}
 }catch(e){if(gen!==appState.fetchGen)return;renderError(content,e&&e.message?String(e.message):"Unexpected error");setStale(true);appState.hasContent=false;}}
function setControlFeedback(message,isError,isPending){const el=$("control-feedback");if(!el)return;el.textContent=message||"";let cls="control-feedback";if(isPending)cls+=" control-pending";else if(isError)cls+=" control-error";else if(message)cls+=" control-ok";el.className=cls;}
function setControlsBusy(busy){document.querySelectorAll(".ctrl-btn").forEach(btn=>{if(busy){btn.dataset.prevDisabled=btn.disabled?"1":"0";btn.disabled=true;}else if(btn.dataset.prevDisabled==="0")btn.disabled=false;});}
async function handleControlClick(btn){const action=btn.getAttribute("data-ctrl"),id=btn.getAttribute("data-id");if(!action||!id)return;const confirmMsg=btn.getAttribute("data-confirm");if(confirmMsg&&!window.confirm(confirmMsg))return;setControlsBusy(true);setControlFeedback("Sending "+action+"…",false,true);let result;try{if(action==="pause")result=await api.pauseExecution(id);else if(action==="resume")result=await api.resumeExecution(id);else if(action==="cancel"){result=await api.controlCancelViaAPI(id);if(!result.ok&&result.status!==403)result=await api.cancelExecution(id);}else if(action==="fleet-cancel")result=await api.cancelFleet(id);else if(action==="retry")result=await api.controlRetry(id);else if(action==="re-run")result=await api.controlRerun(id);else if(action==="approve")result=await api.controlApprove(id,"production_merge");else if(action==="reject")result=await api.controlReject(id,"production_merge");else{setControlFeedback("Unknown action.",true);setControlsBusy(false);return;}}catch(e){setControlFeedback(e&&e.message?String(e.message):"Control failed",true);setControlsBusy(false);return;}if(!result.ok){const msg=result.policyDenied||result.status===403?"Policy denied: "+(result.message||result.control?.error||"not allowed"):formatControlError(result);setControlFeedback(msg,true);setControlsBusy(false);await renderRoute(parseRoute(),{soft:true});return;}setControlFeedback("OK: "+(result.action||result.control?.action||action)+(result.requestId?" req="+result.requestId:""),false);await renderRoute(parseRoute(),{soft:true});}
function wireControls(root){(root||document).querySelectorAll(".ctrl-btn").forEach(btn=>{if(btn.dataset.wired==="1")return;btn.dataset.wired="1";btn.addEventListener("click",e=>{e.preventDefault();handleControlClick(btn);});});}
function wireChrome(){const themeBtn=$("theme-toggle");if(themeBtn)themeBtn.addEventListener("click",()=>{document.body.classList.toggle("dark");themeBtn.setAttribute("aria-pressed",document.body.classList.contains("dark")?"true":"false");});const navToggle=$("nav-toggle"),sidebar=$("sidebar");let backdrop=document.querySelector(".nav-backdrop");if(!backdrop){backdrop=document.createElement("div");backdrop.className="nav-backdrop";backdrop.setAttribute("aria-hidden","true");document.body.appendChild(backdrop);}const setNavOpen=open=>{if(!sidebar||!navToggle)return;sidebar.classList.toggle("open",open);navToggle.setAttribute("aria-expanded",open?"true":"false");backdrop.classList.toggle("visible",open);};if(navToggle&&sidebar){navToggle.addEventListener("click",()=>setNavOpen(!sidebar.classList.contains("open")));backdrop.addEventListener("click",()=>setNavOpen(false));}window.__setNavOpen=setNavOpen;const refresh=$("refresh-btn");if(refresh)refresh.addEventListener("click",()=>renderRoute(parseRoute(),{soft:false}));window.addEventListener("online",()=>{setConnectionStatus();renderRoute(parseRoute(),{soft:true});startPolling(parseRoute());});window.addEventListener("offline",()=>{setConnectionStatus();setStale(true);stopPolling();updateMetaRow();});document.addEventListener("visibilitychange",()=>{if(document.hidden){stopPolling();updateMetaRow();}else{renderRoute(parseRoute(),{soft:true});startPolling(parseRoute());}});}
function registerSW(){if(!(typeof navigator!=="undefined"&&"serviceWorker"in navigator))return;window.addEventListener("load",()=>navigator.serviceWorker.register("/dashboard/sw.js",{scope:"/dashboard/"}).catch(()=>{}));}
function boot(){wireChrome();registerSW();setConnectionStatus();onRouteChange(route=>{if(typeof window.__setNavOpen==="function")window.__setNavOpen(false);else{const sidebar=$("sidebar");if(sidebar)sidebar.classList.remove("open");}stopPolling();renderRoute(route,{soft:false}).then(()=>startPolling(route));});const initial=parseRoute();renderRoute(initial,{soft:false}).then(()=>startPolling(initial));}
// Soft refresh deliberately avoids the loading flash when content is already present.
// The reconciliation contract is represented by { soft: true } and if (!soft || !appState.hasContent).
boot();
